version: "3"

services:
  auth-service:
    image: marciolmm/auth-service:0.99
    ports:
      - "5000:5000"

  email-service:
    image: marciolmm/email-service:1.00
    ports:
      - "5001:5001"

  core-service:
    image: marciolmm/core-service:1.00
    ports:
      - "8080:8080"
