export enum Role {
    ROLE_ADMIN = 'ROLE_ADMIN',
    ROLE_HEADHUNTER = 'ROLE_HEADHUNTER',
    ROLE_CANDIDATE = 'ROLE_CANDIDATE',
    ROLE_RECRUTER_ADMIN = 'ROLE_RECRUTER_ADMIN',
    ROLE_RECRUTER = 'ROLE_RECRUTER'
}
